language: python
sudo: false
notifications:
  email: false

services:
  - postgresql

branches:
  only:
    - master

cache:
  pip: true
  directories:
    - node_modules

env:
  global:
    - CC_TEST_REPORTER_ID=36e83e8985d55acaf2101aa2eb2b70fcfb33e3718e2c822478f678246f3c79c3

matrix:
  include:
    - python: "3.7-dev"
      env: TO_RUN="coverage"
    - python: "3.7-dev"
      env: TO_RUN="postgres-test"
    - python: "3.7-dev"
      env: TO_RUN="lint"
    - python: "3.7-dev"
      env: TO_RUN="js_unit"
    - python: "3.6-dev" # Older python version
      env: TO_RUN="tests"

install:
  - pip install -U wheel
  - pip install coveralls pytest-cov
  - pip install codecov
  - pip install celery[redis]
  - pip install -r requirements.txt

before_script:
  - mkdir -p /tmp/psef/uploads
  - mkdir -p /tmp/psef/mirror_uploads
  - python --version
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  - export DEBUG_ON=True
  - psql -c 'create database travis_ci_test;' -U postgres
  - pip install travis-sphinx
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bash ./.travis/run
  - "[[ $TO_RUN = 'coverage' ]] && travis-sphinx build --source=docs/ || true"

after_success:
  - "[[ $TO_RUN = 'coverage' ]] && ( coveralls; codecov; travis-sphinx deploy -c docs.codegra.de; )"
  - "[[ $TO_RUN = 'js_unit' ]] && ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT"
