"""Add missing migrations

Revision ID: 1c3f3c81901e
Revises: a8074109b57b
Create Date: 2020-10-15 18:05:59.831091

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c3f3c81901e'
down_revision = 'a8074109b57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Group', 'name', existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        'plagiarism_base_code_file',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False
    )
    op.alter_column(
        'plagiarism_base_code_file',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, 'plagiarism_run_old_assignment', type_='foreignkey'
    )
    op.drop_constraint(
        None, 'plagiarism_run_old_assignment', type_='foreignkey'
    )
    op.alter_column('Group', 'name', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
