"""Move LTI 1.1 settings into database

Revision ID: 66337124ad2d
Revises: 70c5c35da75d
Create Date: 2020-09-28 17:32:59.354947

"""
import json

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.sql import text
from sqlalchemy.dialects.postgresql import ENUM, ARRAY

from psef import current_app

# revision identifiers, used by Alembic.
revision = '66337124ad2d'
down_revision = '70c5c35da75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM(
        'Canvas',
        'Blackboard',
        'Sakai',
        'Open edX',
        'Moodle',
        'BrightSpace',
        name='lti1p1lmsnames'
    )
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'LTIProvider', sa.Column('lms_1p1_name', enum, nullable=True)
    )
    op.add_column(
        'LTIProvider',
        sa.Column('lms_1p1_secret', ARRAY(sa.Unicode()), nullable=True)
    )
    bind = op.get_bind()
    for key, (lms, secrets
              ) in current_app.config['LTI_CONSUMER_KEY_SECRETS'].items():
        res = bind.execute(
            text(
                """
        UPDATE "LTIProvider" SET lms_1p1_name = :lms, lms_1p1_secret = :secrets
        WHERE key = :key AND lti_provider_version = 'lti1.1'
        """
            ),
            key=key,
            lms=lms,
            secrets=secrets,
        )
        if res.rowcount == 0:
            bind.execute(
                text(
                    """
                INSERT INTO "LTIProvider" (id, lms_1p1_name, lms_1p1_secret, key, lti_provider_version)
                VALUES (uuid_generate_v4(), :lms, :secrets, :key, 'lti1.1')
        """
                ),
                key=key,
                lms=lms,
                secrets=secrets,
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LTIProvider', 'lms_1p1_secret')
    op.drop_column('LTIProvider', 'lms_1p1_name')
    # ### end Alembic commands ###
