"""Add plagiarism run base code and old assignment tables

Revision ID: 693eee0d8372
Revises: 70c5c35da75d
Create Date: 2020-09-24 16:14:20.171727

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '693eee0d8372'
down_revision = '70c5c35da75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plagiarism_base_code_file',
        sa.Column('name', sa.Unicode(), nullable=False),
        sa.Column('filename', sa.Unicode(), nullable=True),
        sa.Column(
            'modification_date', sa.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column(
            'id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column('plagiarism_run_id', sa.Integer(), nullable=False),
        sa.Column('is_directory', sa.Boolean(), nullable=False),
        sa.Column(
            'parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['plagiarism_base_code_file.id'],
        ),
        sa.ForeignKeyConstraint(['plagiarism_run_id'], ['PlagiarismRun.id'],
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'plagiarism_run_old_assignment',
        sa.Column('old_assignment_id', sa.Integer(), nullable=False),
        sa.Column('plagiarism_run_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['old_assignment_id'],
            ['Assignment.id'],
        ),
        sa.ForeignKeyConstraint(
            ['plagiarism_run_id'],
            ['PlagiarismRun.id'],
        ),
        sa.PrimaryKeyConstraint('old_assignment_id', 'plagiarism_run_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plagiarism_run_old_assignment')
    op.drop_table('plagiarism_base_code_file')
    # ### end Alembic commands ###
