"""Add description_type column to RubricItem and RubricRow tables

Revision ID: 6979279573d0
Revises: 3a74e01ebcbf9099d761
Create Date: 2020-09-10 14:58:51.840449

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '6979279573d0'
down_revision = '3a74e01ebcbf9099d761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM('plain_text', 'markdown', name='rubricdescriptiontype')
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column('RubricItem', sa.Column('description_type', enum, server_default='plain_text', nullable=False))
    op.add_column('RubricRow', sa.Column('description_type', enum, server_default='plain_text', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RubricRow', 'description_type')
    op.drop_column('RubricItem', 'description_type')
    enum = ENUM(name='rubricdescriptiontype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
