"""Add code_quality AutoTest step type

Revision ID: 6b9c3e8db3d4
Revises: e1d03bcf85be
Create Date: 2020-10-12 19:29:28.166377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '6b9c3e8db3d4'
down_revision = 'e1d03bcf85be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autoteststeptesttype', ['check_points', 'custom_output', 'io_test', 'junit_test', 'run_program'], ['check_points', 'code_quality', 'custom_output', 'io_test', 'junit_test', 'run_program'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autoteststeptesttype', ['check_points', 'code_quality', 'custom_output', 'io_test', 'junit_test', 'run_program'], ['check_points', 'custom_output', 'io_test', 'junit_test', 'run_program'])
    # ### end Alembic commands ###
