"""empty message

Revision ID: 6ef95af38a43
Revises: 693eee0d8372
Create Date: 2020-09-24 16:20:09.613019

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '6ef95af38a43'
down_revision = '693eee0d8372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plagiarism_run_old_assignments',
        sa.Column('old_assignment_id', sa.Integer(), nullable=False),
        sa.Column('plagiarism_run_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['old_assignment_id'],
            ['Assignment.id'],
        ),
        sa.ForeignKeyConstraint(
            ['plagiarism_run_id'],
            ['PlagiarismRun.id'],
        ), sa.PrimaryKeyConstraint('old_assignment_id', 'plagiarism_run_id')
    )
    op.drop_table('plagiarism_run_old_assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plagiarism_run_old_assignment',
        sa.Column(
            'old_assignment_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'plagiarism_run_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['old_assignment_id'], ['Assignment.id'],
            name='plagiarism_run_old_assignment_old_assignment_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['plagiarism_run_id'], ['PlagiarismRun.id'],
            name='plagiarism_run_old_assignment_plagiarism_run_id_fkey'
        ),
        sa.PrimaryKeyConstraint(
            'old_assignment_id',
            'plagiarism_run_id',
            name='plagiarism_run_old_assignment_pkey'
        )
    )
    op.drop_table('plagiarism_run_old_assignments')
    # ### end Alembic commands ###
