"""Add ``NULL`` constraint on ``plagiarism_case_id``.

Revision ID: 70c5c35da75d
Revises: 3a74e01ebcbf9099d761
Create Date: 2020-09-21 19:01:23.255894

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '70c5c35da75d'
down_revision = '3a74e01ebcbf9099d761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PlagiarismMatch', 'plagiarism_case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PlagiarismMatch', 'plagiarism_case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
