"""Add cascades on plagiarism_run_old_assignment fks

Revision ID: 9d7e00d79d47
Revises: adffe757e428
Create Date: 2020-10-15 18:21:15.406647

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9d7e00d79d47'
down_revision = 'adffe757e428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'plagiarism_run_old_assignment_old_assignment_id_fkey',
        'plagiarism_run_old_assignment',
        type_='foreignkey'
    )
    op.drop_constraint(
        'plagiarism_run_old_assignment_plagiarism_run_id_fkey',
        'plagiarism_run_old_assignment',
        type_='foreignkey'
    )
    op.create_foreign_key(
        'plagiarism_run_old_assignment_plagiarism_run_id_fkey',
        'plagiarism_run_old_assignment',
        'PlagiarismRun', ['plagiarism_run_id'], ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'plagiarism_run_old_assignment_old_assignment_id_fkey',
        'plagiarism_run_old_assignment',
        'Assignment', ['old_assignment_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'plagiarism_run_old_assignment_old_assignment_id_fkey',
        'plagiarism_run_old_assignment',
        type_='foreignkey'
    )
    op.drop_constraint(
        'plagiarism_run_old_assignment_plagiarism_run_id_fkey',
        'plagiarism_run_old_assignment',
        type_='foreignkey'
    )
    op.create_foreign_key(
        'plagiarism_run_old_assignment_plagiarism_run_id_fkey',
        'plagiarism_run_old_assignment', 'Assignment', ['old_assignment_id'],
        ['id']
    )
    op.create_foreign_key(
        'plagiarism_run_old_assignment_old_assignment_id_fkey',
        'plagiarism_run_old_assignment', 'PlagiarismRun',
        ['plagiarism_run_id'], ['id']
    )
    # ### end Alembic commands ###
