"""Add ui_preferences table

Revision ID: a8074109b57b
Revises: 58781142620e
Create Date: 2020-10-02 10:44:02.658084

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'a8074109b57b'
down_revision = '58781142620e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ui_preference', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            'name',
            sa.Enum('rubric_editor_v2', name='ui_preference_name'),
            nullable=False
        ), sa.Column('value', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('user_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ui_preference')
    ENUM(name='ui_preference_name').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
