"""Add state enum to course.

Revision ID: abd0b88b46e3
Revises: 2a6d3495e75f
Create Date: 2020-09-04 14:00:37.060874

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'abd0b88b46e3'
down_revision = '2a6d3495e75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM('visible', 'archived', 'deleted', name='coursestate')
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'Course',
        sa.Column('state', enum, server_default='visible', nullable=False)
    )
    op.add_column(
        'Course',
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default='NOW()'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course', 'updated_at')
    op.drop_column('Course', 'state')
    # ### end Alembic commands ###
