"""Add `auto_test_quality_comment` table

Revision ID: e1d03bcf85be
Revises: a8074109b57b
Create Date: 2020-10-11 22:29:21.781288

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1d03bcf85be'
down_revision = 'a8074109b57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auto_test_quality_comment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('auto_test_step_id', sa.Integer(), nullable=False),
        sa.Column('auto_test_result_id', sa.Integer(), nullable=False),
        sa.Column('File_id', sa.Integer(), nullable=False),
        sa.Column('line_start', sa.Integer(), nullable=False),
        sa.Column('line_end', sa.Integer(), nullable=False),
        sa.Column('column_start', sa.Integer(), nullable=False),
        sa.Column('column_end', sa.Integer(), nullable=True),
        sa.Column('origin', sa.Unicode(), nullable=False),
        sa.Column('quality_code', sa.Unicode(), nullable=True),
        sa.Column(
            'severity',
            sa.Enum(
                'info',
                'warning',
                'error',
                'fatal',
                name='qualitycommentseverity'
            ),
            nullable=False
        ), sa.Column('comment', sa.Unicode(), nullable=False),
        sa.ForeignKeyConstraint(['File_id'], ['File.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['auto_test_result_id'], ['AutoTestResult.id'],
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['auto_test_step_id'], ['AutoTestStep.id'],
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_test_quality_comment')
    # ### end Alembic commands ###
