"""This file contains all wrapper scripts used by CodeGrade in
the "Code Quality" AutoTest step.

.. warning::

  
  Do not edit this enum as it is automatically generated by
  "generate_code_quality_wrappers.py".

SPDX-License-Identifier: AGPL-3.0-only
"""
# pylint: skip-file
# flake8: noqa=E501
# yapf: disable

import typing as t
import dataclasses

import cg_enum


@dataclasses.dataclass
class _CodeQualityWrapper:
    name: str
    source: t.Optional[str]
    executable: t.Optional[str]


class CodeQualityWrapper(cg_enum.CGEnum):
    custom = _CodeQualityWrapper(name='custom', source=None, executable=None)
    cg_checkstyle = _CodeQualityWrapper(name='checkstyle', source='cg_checkstyle.py', executable='cg_checkstyle')
    cg_eslint = _CodeQualityWrapper(name='eslint', source='cg_eslint.py', executable='cg_eslint')
    cg_flake8 = _CodeQualityWrapper(name='flake8', source='cg_flake8.py', executable='cg_flake8')
    cg_pmd = _CodeQualityWrapper(name='pmd', source='cg_pmd.py', executable='cg_pmd')
    cg_pylint = _CodeQualityWrapper(name='pylint', source='cg_pylint.py', executable='cg_pylint')
