"""This file contains all wrapper scripts used by CodeGrade in
the "Code Quality" AutoTest step.

.. warning::

  
  Do not edit this enum as it is automatically generated by
  "generate_code_quality_wrappers.py".

SPDX-License-Identifier: AGPL-3.0-only
"""
# pylint: skip-file
# flake8: noqa=E501
# yapf: disable

import cg_enum

class CodeQualityWrapper(cg_enum.CGEnum):
    custom = 'custom'
    cg_eslint = 'cg-eslint'
    cg_pmd = 'cg-pmd'
    cg_pylint = 'cg-pylint'
