#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only

import os
import sys
import json
import subprocess
import xml.etree.ElementTree as ET

STUDENT = os.environ['STUDENT']
# {CHECKSTYLE_PATH} is to be substituted by the AT runner.
CHECKSTYLE_JAR = '{CHECKSTYLE_PATH}/checkstyle.jar'


def handle_file_output(file_el):
    msgs = []

    for error_el in file_el:
        if error_el.tag != 'error':  # pragma: no cover
            continue

        filename = file_el.attrib['name']
        attrib = error_el.attrib
        line = int(attrib['line'])

        filename = filename[len(STUDENT):]
        if filename.startswith('./'):
            filename = filename[2:]

        msgs.append(
            dict(
                [
                    ('origin', 'Checkstyle'),
                    ('msg', attrib['message']),
                    ('code', attrib['source']),
                    ('severity', attrib.get('severity', 'warning')),
                    ('line', dict([
                        ('start', line),
                        ('end', line),
                    ])),
                    (
                        'column',
                        dict(
                            [
                                ('start', int(attrib.get('column', 1))),
                                ('end', None),
                            ]
                        )
                    ),
                    ('path', filename.split('/')),
                ]
            ),
        )

    return msgs


def main() -> None:
    """Run Checkstyle
    """

    # The check for success is something we really don't want here.
    proc = subprocess.run(  # pylint: disable=subprocess-run-check
        [
            'java',
            '-jar', CHECKSTYLE_JAR,
            '-f', 'xml',
            *sys.argv[1:],
            '.',
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )

    if proc.returncode == 254:
        print(
            'The given submission could not be parsed as Java:\n',
            proc.stderr,
            file=sys.stderr,
        )
        sys.exit(proc.returncode)

    try:
        output = ET.fromstring(proc.stdout.decode('utf8'))
    except ET.ParseError:
        print(
            'The output could not be parsed as XML:\n',
            proc.stderr,
            file=sys.stderr,
        )
        sys.exit(1)

    comments = [
        err for el in output for err in handle_file_output(el)
        if el.tag == 'file'
    ]

    if comments:
        api_input = json.dumps(
            dict([
                ('op', 'put_comments'),
                ('comments', comments),
            ]),
        )
        api_proc = subprocess.run(
            ['cg-api'], input=api_input.encode('utf8'), check=False
        )
        sys.exit(api_proc.returncode)


if __name__ == '__main__':
    main()
