#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only

import os
import sys
import json
import tempfile
import subprocess

STUDENT = os.environ['STUDENT']


def handle_file_output(f) -> str:
    msgs = []

    for message in f['messages']:
        if message.get('fatal', False):
            severity = 'fatal'
        elif message['severity'] == 1:
            severity = 'warning'
        elif message['severity'] == 2:
            severity = 'error'

        msgs.append({
            'origin': 'ESLint',
            'msg': message['message'],
            'code': message['ruleId'],
            'severity': severity,
            'line': {
                'start': message['line'],
                'end': message.get('endLine', message['line']),
            },
            'column': {
                'start': message['column'],
                'end': message.get('endColumn', None),
            },
            'path': f['filePath'][len(STUDENT):].split('/'),
        })

    return msgs


def main() -> None:
    """Run ESLint.
    """

    npm_root = subprocess.check_output(['npm', 'root', '-g'])

    # The check for success is something we really don't want here.
    proc = subprocess.run(  # pylint: disable=subprocess-run-check
        [
            'eslint',
            '--format', 'json',
            '--resolve-plugins-relative-to', npm_root,
            # Prevent students from modifying the config.
            '--no-eslintrc',
            '--no-inline-config',
            '--report-unused-disable-directives',
            *sys.argv[1:],
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    # Exit code 1 means that linting was successful but that errors
    # were found.
    if proc.returncode not in {0, 1}:
        print('ESLint crashed, stdout:\n', proc.stderr, file=sys.stderr)
        exit(proc.returncode)

    output = json.dumps({
        'op': 'put_comments',
        'comments': [
            c
            for f in json.loads(proc.stdout.decode('utf8'))
            for c in handle_file_output(f)
        ],
    })

    subprocess.run(['cg-api'], input=output.encode('utf8'))


if __name__ == '__main__':
    main()
