#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only

import os
import sys
import json
import uuid
import subprocess


def handle_error(filename, line, col, code, msg):
    if filename.startswith('./'):
        filename = filename[2:]

    if code.startswith('E') or code.startswith('F'):
        severity = 'error'
    elif code.startswith('W'):
        severity = 'warning'
    elif code.startswith('C') or code.startswith('N8'):
        severity = 'info'

    return dict(
        [
            ('origin', 'Flake8'),
            ('msg', msg),
            ('code', code),
            ('severity', severity),
            ('line', dict([
                ('start', int(line)),
                ('end', int(line)),
            ])),
            ('column', dict([
                ('start', int(col)),
                ('end', None),
            ])),
            ('path', filename.split('/')),
        ]
    )


def main() -> None:
    """Run Flake8.
    """

    # This is not guessable
    sep = str(uuid.uuid4())
    fmt = '%(path)s{{0}}%(row)d{{0}}%(col)d{{0}}%(code)s{{0}}%(text)s'.format(sep)

    # The check for success is something we really don't want here.
    proc = subprocess.run(  # pylint: disable=subprocess-run-check
        [
            'flake8',
            '--disable-noqa',
            '--format', fmt,
            '--exit-zero',
            *sys.argv[1:],
        ],
        capture_output=True,
        text=True,
    )

    if proc.returncode != 0:
        print('Flake8 crashed:\n', proc.stderr, file=sys.stderr)
        sys.exit(proc.returncode)

    comments = [
        handle_error(*err.split(sep))
        for err in proc.stdout.splitlines()
        if len(err.split(sep)) == 5
    ]

    if comments:
        output = json.dumps(
            dict([
                ('op', 'put_comments'),
                ('comments', comments),
            ]),
        )
        api_proc = subprocess.run(
            ['cg-api'], input=output.encode('utf8'), check=False
        )


if __name__ == '__main__':
    main()
