/**
This file contains all wrapper scripts used by CodeGrade in
the "Code Quality" AutoTest step.


Do not edit this enum as it is automatically generated by
"generate_code_quality_wrappers.py".

SPDX-License-Identifier: AGPL-3.0-only
*/
/* eslint-disable */

export class CodeQualityWrapper {
    constructor(public key: string, public name: string) {
        Object.freeze(this);
    }
}

export type CodeQualityWrapperName = keyof typeof codeQualityWrappers;

export const codeQualityWrappers = Object.freeze({
    cg_checkstyle: new CodeQualityWrapper('cg_checkstyle', 'checkstyle'),
    cg_eslint: new CodeQualityWrapper('cg_eslint', 'eslint'),
    cg_flake8: new CodeQualityWrapper('cg_flake8', 'flake8'),
    cg_pmd: new CodeQualityWrapper('cg_pmd', 'pmd'),
    cg_pylint: new CodeQualityWrapper('cg_pylint', 'pylint'),
    custom: new CodeQualityWrapper('custom', 'custom'),
} as const);
