/**
This file contains all wrapper scripts used by CodeGrade in
the "Code Quality" AutoTest step.


Do not edit this enum as it is automatically generated by
"generate_code_quality_wrappers.py".

SPDX-License-Identifier: AGPL-3.0-only
*/
/* eslint-disable */

export enum CodeQualityWrapper {
    custom = 'custom',
    cg_eslint = 'cg_eslint',
    cg_pmd = 'cg_pmd',
    cg_pylint = 'cg_pylint'
}
