"""Add "assigned" runner state

Revision ID: 5ba130d6e047
Revises: 5203c1c439bb
Create Date: 2020-09-06 13:56:08.800327

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5ba130d6e047'
down_revision = '5203c1c439bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public', 'runnerstate', [
            'cleaned', 'cleaning', 'creating', 'not_running', 'running',
            'started'
        ], [
            'assigned', 'cleaned', 'cleaning', 'creating', 'not_running',
            'running', 'started'
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public', 'runnerstate', [
            'assigned', 'cleaned', 'cleaning', 'creating', 'not_running',
            'running', 'started'
        ], [
            'cleaned', 'cleaning', 'creating', 'not_running', 'running',
            'started'
        ]
    )
    # ### end Alembic commands ###
