"""Add cache table

Revision ID: 9144f561c260
Revises: db301e37a2a7
Create Date: 2020-10-14 13:25:56.236105

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9144f561c260'
down_revision = 'db301e37a2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cache', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('expires', sa.Interval(), nullable=False),
        sa.Column('namespace', sa.Unicode(), nullable=False),
        sa.Column('key', sa.Unicode(), nullable=False),
        sa.Column(
            'value', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'namespace_key_index', 'cache', ['key', 'namespace'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('namespace_key_index', table_name='cache')
    op.drop_table('cache')
    # ### end Alembic commands ###
