"""Add new setting to database

Revision ID: db301e37a2a7
Revises: 5ba130d6e047
Create Date: 2020-10-07 11:21:45.523012

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'db301e37a2a7'
down_revision = '5ba130d6e047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public', 'possiblesetting', ['minimum_amount_extra_runners'],
        ['assigned_grace_period', 'minimum_amount_extra_runners']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public', 'possiblesetting',
        ['assigned_grace_period', 'minimum_amount_extra_runners'],
        ['minimum_amount_extra_runners']
    )
    # ### end Alembic commands ###
