---
name: "Back-end tests"

"on":
  pull_request:
    branches:
      - master
      - stable
  push:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.7
          - 3.8
        auto-test-runner:
          - "yes"
          - "no"

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: travis_ci_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - name: "Checkout code"
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        uses: actions/checkout@v1

      - name: "Set up Python ${{ matrix.python-version }}"
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: cache for python
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        run: ./.github/scripts/install.bash skip_npm

      - name: Install pytest timeout
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        run: pip install pytest-timeout

      - name: Make needed directories
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        run: |
          mkdir -p /tmp/psef/uploads
          mkdir -p /tmp/psef/mirror_uploads

      - name: Run tests
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        run: ./.github/scripts/run_backend_tests.bash
        env:
          RUN_AT_ONLY: ${{ matrix.auto-test-runner }}

      - name: Upload to coveralls
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        run: coveralls
        continue-on-error: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS }}

      - name: Upload to codecov
        if: matrix.python-version == '3.7' || matrix.auto-test-runner == 'no'
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
