---
name: "Changelog"

on:
  pull_request:
    branches:
      - master
      - stable
  issue_comment:
    types:
      - created

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Look for ignore comment
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '!ignore changelog'
          reaction: eyes
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: "Checkout code"
        if: steps.check.outputs.triggered == 'false'
        uses: actions/checkout@v1

      - name: Check if changelog was updated
        if: steps.check.outputs.triggered == 'false'
        run: ./.github/scripts/ensure_changelog_updated.sh
