---
name: "Changelog updated"

on:
  pull_request:
    branches:
      - master
      - stable
  issue_comment:
    types:
      - created

jobs:
  changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Look for ignore comment
        uses: khan/pull-request-comment-trigger@master
        id: ignore_changelog
        with:
          trigger: '!ignore changelog'
          reaction: eyes
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Found ignore comment
        run: printf '%s\n' '${{ steps.ignore_changelog.outputs.triggered }}'

      - name: "Checkout code"
        if: steps.ignore_changelog.outputs.triggered == 'false'
        uses: actions/checkout@v1

      - name: Check if changelog was updated
        if: steps.ignore_changelog.outputs.triggered == 'false'
        run: ./.github/scripts/ensure_file_changed.sh docs/about/changelog.rst
