---
name: "Linters"

"on":
  pull_request:
    branches:
      - master
      - stable
  push:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: cache for npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-node-${{ hashFiles('npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: cache for python
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('broker_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: ./.github/scripts/install.bash

      - name: Make needed directories
        run: |
          mkdir -p /tmp/psef/uploads
          mkdir -p /tmp/psef/mirror_uploads

      - name: Run linters
        run: ./.github/scripts/run_linters.bash

      - name: Deploy docs
        uses: JacksonMaxfield/github-pages-deploy-action-python@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/_build/html_deploy  # The folder the action should deploy.
          BUILD_SCRIPT: ( cd docs && rm -rf _build/html_deploy/* && mv _build/html/* _build/html_deploy/ && touch _build/html_deploy/.nojekyll && echo docs.codegra.de > _build/html_deploy/CNAME )
        if: github.ref == 'refs/heads/master'
